language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t leyanshrestha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leyanshrestha/docker-react npm run test